In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('oer_records.csv')

In [25]:
df.head()

,doi,source_pdf,title,abstract,material,substrate,electrolyte,overpotential_mV,current_density,confidence,extraction_note,anchor_found,anchor_sentence
0,10.1038/s41598-026-52116-3,Sustainable_synthesis_of_Ni-doped_Co3O4graphen...,© The Author(s) 2026. Open Access This article...,Developing sustainable and cost-effective elec...,Ni-Co3O4@G,glassy carbon,1 M KOH,NaN,NaN,0.55,material_without_anchor,False,NaN
1,10.1038/ncomms5345,Electrochemical_tuning_of_layered_lithium_tran...,1 Department of Material Science and Engineeri...,Searching for low-cost and efﬁcient catalysts ...,NaN,foil,0.1 M KOH,NaN,NaN,0.30,missing_anchor,False,NaN
2,10.1038/ncomms9249,Covalency-reinforced_oxygen_evolution_reaction...,OPEN,The oxygen evolution reaction that occurs duri...,Ba0.5Sr0.5Co0.8Fe0.2O3,glassy carbon,0.1 M KOH,NaN,NaN,0.55,material_without_anchor,False,NaN
3,10.1038/s41467-022-28260-5,Electrode_reconstruction_strategy_for_oxygen_e...,OPEN,Computational calculations and experimental st...,CF-FeSO,foam,1 M KOH,200.0,100.0,1.00,nonstandard_current_density,True,3f. CF-FeSO exhibited a cell voltage of 1.61 V...
4,10.1038/s41467-025-65626-x,Atomic-scale_insights_into_surface_reconstruct...,Atomic-scale insights into surface reconstruct...,Optimizing the activity and longevity of oxyge...,CoCr2O4,glassy carbon,1.0 M KOH,370.0,10.0,1.00,complete,True,S2). CoCr2O4 exhibited slightly better OER act...

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doi               401 non-null    str
 1   source_pdf        402 non-null    str
 2   title             402 non-null    str
 3   abstract          402 non-null    str
 4   material          370 non-null    str
 5   substrate         363 non-null    str
 6   electrolyte       344 non-null    str
 7   overpotential_mV  253 non-null    float64
 8   current_density   253 non-null    float64
 9   confidence        402 non-null    float64
 10  extraction_note   402 non-null    str
 11  anchor_found      402 non-null    bool
 12  anchor_sentence   253 non-null    str
dtypes: bool(1), float64(3), str(9)
memory usage: 38.2 KB

In [27]:
df.shape

(402, 13)

In [28]:
df = df[df['anchor_found']]

In [29]:
df.shape

(253, 13)

In [30]:
df = df.drop(['title', 'anchor_sentence', 'anchor_found', 'extraction_note'], axis=1)

In [31]:
df.head()

,doi,source_pdf,abstract,material,substrate,electrolyte,overpotential_mV,current_density,confidence
3,10.1038/s41467-022-28260-5,Electrode_reconstruction_strategy_for_oxygen_e...,Computational calculations and experimental st...,CF-FeSO,foam,1 M KOH,200.0,100.0,1.0
4,10.1038/s41467-025-65626-x,Atomic-scale_insights_into_surface_reconstruct...,Optimizing the activity and longevity of oxyge...,CoCr2O4,glassy carbon,1.0 M KOH,370.0,10.0,1.0
8,10.1038/s41467-025-55857-3,Operando_monitoring_of_the_functional_role_of_...,The complexity of the intrinsic oxygen evoluti...,CoII/FeIIIO6,carbon paper,1.0 M KOH,225.0,20.0,1.0
13,10.1038/s41467-024-46801-y,The_formation_of_unsaturated_IrOxin_SrIrO3by_c...,Electrocatalytic water splitting is a promisin...,SI6C1,mesh,0.5 M H2SO4,245.0,10.0,1.0
16,10.1038/s41467-021-26025-0,Restructuring_highly_electron-deficient_metal-...,The poor catalyst stability in acidic oxidatio...,MoO3,foil,0.5 M H2SO4,156.0,10.0,1.0

In [32]:
df.to_csv('oer_limpo_2.csv', index=False)

In [35]:
has_duplicates = df['doi'].duplicated().any()
print(has_duplicates)

False